=== damian-damjanovic-hn/JSON-Schemas/m2_product_schema_from_sample_1.json
{
    "$schema": "https://json-schema.org/draft/2020-12/schema",
    "type": "object",
    "required": [
        "attribute_set_id",
        "created_at",
        "custom_attributes",
        "extension_attributes",
        "id",
        "media_gallery_entries",
        "name",
        "options",
        "price",
        "product_links",
        "sku",
        "status",
        "tier_prices",
        "type_id",
        "updated_at",
        "visibility"
    ],
    "properties": {
        "id": {
            "type": "integer"
        },
        "sku": {
            "type": "string"
        },
        "name": {
            "type": "string"
        },
        "attribute_set_id": {
            "type": "integer"
        },
        "price": {
            "type": "integer"
        },
        "status": {
            "type": "integer"
        },
        "visibility": {
            "type": "integer"
        },
        "type_id": {
            "type": "string"
        },
        "created_at": {
            "type": "string"
        },
        "updated_at": {
            "type": "string"
        },
        "extension_attributes": {
            "type": "object",
            "required": [
                "website_ids"
            ],
            "properties": {
                "website_ids": {
                    "type": "array",
                    "items": {
                        "type": "integer"
                    }
                }
            }
        },
        "product_links": {
            "type": "array"
        },
        "options": {
            "type": "array"
        },
        "media_gallery_entries": {
            "type": "array"
        },
        "tier_prices": {
            "type": "array"
        },
        "custom_attributes": {
            "type": "array",
            "items": {
                "type": "object",
                "properties": {
                    "attribute_code": {
                        "type": "string"
                    },
                    "value": {
                        "anyOf": [
                            {
                                "type": "array"
                            },
                            {
                                "type": "string"
                            }
                        ]
                    }
                },
                "required": [
                    "attribute_code",
                    "value"
                ]
            }
        }
    }
}

=== damian-damjanovic-hn/JSON-Schemas/m2_product_sample_1.json
{
    "id": 753918,
    "sku": "153105",
    "name": "153105 SPEED HUMP YELLOW&BLACK 129X32.5X",
    "attribute_set_id": 458,
    "price": 91,
    "status": 2,
    "visibility": 3,
    "type_id": "simple",
    "created_at": "2024-11-12 00:30:32",
    "updated_at": "2024-11-12 00:30:32",
    "extension_attributes": {
        "website_ids": [
            1
        ]
    },
    "product_links": [
    ],
    "options": [
    ],
    "media_gallery_entries": [
    ],
    "tier_prices": [
    ],
    "custom_attributes": [
        {
            "attribute_code": "url_key",
            "value": "153105-speed-hump-yellow-black-129x32-5x"
        },
        {
            "attribute_code": "options_container",
            "value": "container2"
        },
        {
            "attribute_code": "description",
            "value": "Built from masterdata product record #585420"
        },
        {
            "attribute_code": "cost",
            "value": "77.040000"
        },
        {
            "attribute_code": "article_i_d",
            "value": "12511658"
        },
        {
            "attribute_code": "oms_department",
            "value": "11"
        },
        {
            "attribute_code": "oms_ffgroup",
            "value": "211"
        },
        {
            "attribute_code": "msrp_display_actual_price_type",
            "value": "0"
        },
        {
            "attribute_code": "barcode_gtin",
            "value": "8720287178521"
        },
        {
            "attribute_code": "product_staging",
            "value": "87306"
        },
        {
            "attribute_code": "required_options",
            "value": "0"
        },
        {
            "attribute_code": "has_options",
            "value": "0"
        },
        {
            "attribute_code": "tax_class_id",
            "value": "2"
        },
        {
            "attribute_code": "is_imported",
            "value": "1"
        },
        {
            "attribute_code": "is_googleshopping",
            "value": "1"
        },
        {
            "attribute_code": "category_ids",
            "value": [
            ]
        },
        {
            "attribute_code": "is_returnable",
            "value": "2"
        },
        {
            "attribute_code": "offer_type",
            "value": "87246"
        },
        {
            "attribute_code": "value_statement",
            "value": "67197,67201,67223"
        },
        {
            "attribute_code": "msg_availability",
            "value": "10341"
        },
        {
            "attribute_code": "msg_availability_type",
            "value": "35494"
        }
    ]
}
